### ISSUE TITLE
Test List

### ISSUE THREAD

**Issue by Bara** [Bara/LastRequest#20]
- [x] LR_GivePlayerItem/SetAmmo
- [x] Knife Thirdperson
- [x] #14 (not for all?)
- [x] Drop block during shot 4 shot
- [x] m_aimPunchAngle error
- [x] Gun Toss weapon not saved
- [x] Give Weapon Glitch ( Issue: #21 )
- [x] Full Name in end message
- [x] Give old weapons back ( Issue: #9 )
- [x] Game Mode in End Message
- [x] Player Reset not working
- [x] Correct Reset (LR Stop) on Menu Timeout
- [x] No slay if timeout punishment is 0
- [x] Force Accept ( #22 )
- [x] No game details menu on force accept
- [ ] Speed/Gravity Reset after Knife Fight
- [ ] LR Player can attack/kill non LR Player(?)
